from .base import db

class Equipment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    heatingType = db.Column(db.String(200), unique=False, nullable=False)
    heatingAge = db.Column(db.Integer, unique=False, nullable=False)
    heatingCapacity = db.Column(db.Integer, unique=False, nullable=False)
    waterHeatingAge = db.Column(db.Integer, unique=False, nullable=False)
    waterHeatingType = db.Column(db.String(200), unique=False, nullable=False)
    inputCapacity = db.Column(db.Integer, unique=False, nullable=False)
    fridgeCount =db.Column(db.Integer, unique=False, nullable=False)
    freezerCount =db.Column(db.Integer, unique=False, nullable=False)
    microwaveCount =db.Column(db.Integer, unique=False, nullable=False)
    blenderCount =db.Column(db.Integer, unique=False, nullable=False)
    coffeeMakerCount =db.Column(db.Integer, unique=False, nullable=False)
    computerCount =db.Column(db.Integer, unique=False, nullable=False)
    dishwasherCount =db.Column(db.Integer, unique=False, nullable=False)
    washerCount =db.Column(db.Integer, unique=False, nullable=False)
    dryerCount =db.Column(db.Integer, unique=False, nullable=False)
    garageOpenerCount =db.Column(db.Integer, unique=False, nullable=False)
    kettleCount =db.Column(db.Integer, unique=False, nullable=False)
    ovenCount =db.Column(db.Integer, unique=False, nullable=False)
    toasterCount =db.Column(db.Integer, unique=False, nullable=False)
    toasterOvenCount =db.Column(db.Integer, unique=False, nullable=False)
    sumpPumpCount =db.Column(db.Integer, unique=False, nullable=False)
    vacuumCount =db.Column(db.Integer, unique=False, nullable=False)
    customer_id = db.Column(db.Integer, db.ForeignKey('customer.id'))
